'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AngelAndroid_v2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3g() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3g", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Abov_mid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Abov_mid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to باستخدام البرنامج ، فإنك توافق على الكل أدناه:
        '''1: أنت مسؤول عن جميع أنواع الاستخدامات في هذا البرنامج.
        '''2: قم بتثبيت (CypherRat  Apk) فقط على الهواتف التي لديك أذونات لها.
        '''3: مطور هذه البرامج غير مسؤول عن أي نوع من الاستخدامات غير القانونية.
        '''4: هذا البرنامج مصمم للاستخدام الشخصي فقط.
        '''5: لا تبيع هذا البرنامج ، إذا حاولت بيع هذا البرنامج ، فقد يفرض عليك المطور رسومًا.
        '''6:تاكد من التحميل من قناتنا على التلغرام : t.me/evlfdev
        '''------------------------.
        '''</summary>
        Friend ReadOnly Property ARPolice() As String
            Get
                Return ResourceManager.GetString("ARPolice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C:\ProgramData\cconfig.
        '''</summary>
        Friend ReadOnly Property DataP() As String
            Get
                Return ResourceManager.GetString("DataP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property disconnected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("disconnected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;action android:name=&quot;[HIDE_CODE]&quot;/&gt;.
        '''</summary>
        Friend ReadOnly Property HIDECODE() As String
            Get
                Return ResourceManager.GetString("HIDECODE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("log", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LOGO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOGO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to c4zNc8cgBpaC1Xnzsd71BdIEjHm+/cp4gXXrYx1KlpAlf192T72ZxERb/E6hQkj8Yn98Vqy8Io1u
        '''4PHakKbelS3OXML7b3EDsJVfrihgu2WBaxdewl2OGAZhApSYHBap5fmAOFKwNCNnPIn7iGzEFH/6
        '''o0fxhQrMWuGbAJ55yz3lxZrM6S/mNEIXwZH5O3Gj+CMa6XmEr+5brNo9W3TxGu5kvzOd977fMtdp
        '''ZQKOWVq4v+dYm43WQsd3zwRFISr6zEhvly38vOKRYTJVbFOyp5/xqKRJ7fGbY3xgt0GRsrxya2/M
        '''V26HhrCtDdH2z0k3f0s1Glg/0vhMjYxegk6kuCgg7LohB6z1EQx4Zmvk18w8YcJvLhrmBtPrX2w3
        '''dk0XHBMZpRqlpP/wHSBuCSJUvIeGhJ7/1cC+u+ON42MQUaqduCuLysZ+Fd0ZGVCpEgc9ceYHha3n
        '''Nkz54jxY3Gs15QzjEJ10WnP0z/CKJPmV+EtU8Oc2uDPI [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LOGS() As String
            Get
                Return ResourceManager.GetString("LOGS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property low() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("low", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''&lt;head&gt;
        '''&lt;meta charset= 
        '''&lt;title&gt;\\name_victim:\\&lt;/title&gt;
        '''&lt;meta name= 
        '''&lt;script src= 
        '''&lt;link href= 
        '''&lt;style&gt;
        '''body { margin:0; padding:0; }
        '''#map { position:absolute; top:0; bottom:0; width:100%; }
        '''&lt;/style&gt;
        '''&lt;/head&gt;
        '''&lt;body&gt;
        ''' &lt;div id= 
        ''' &lt;script&gt;
        '''mapboxgl.accessToken =  
        ''' var map = new mapboxgl.Map({
        '''container:  
        '''style:  
        '''center: [\\:\\,\\:\\],
        '''zoom: 15
        '''});
        ''' var size = 200;
        ''' var pulsingDot = {
        '''width: size,
        '''height: size,
        '''data: new Uint8Array(size * size * 4),
        ''' onAdd: function() [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property map() As String
            Get
                Return ResourceManager.GetString("map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property max() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("max", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MYSTUB() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MYSTUB", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MYSTUBTEN() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MYSTUBTEN", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notifi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notifi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OFF_LOCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OFF_LOCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ON_LOCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ON_LOCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PikPng_com_phone_frame_png_962974() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PikPng_com_phone_frame_png_962974", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to By using the software , you Accepted to All Below : 
        '''1 : You are the responsible for All kind of uses in this software.
        '''2 : Only install (CypherRat Apk ) on phones you have permissions to.
        '''3 : Developer of these software is Not Responsible for Any kind of  illegal uses.
        '''4 : This Program is Build for Personal use Only.
        '''5 : Don 
        '''6: Make sure to get it from Telegram: t.me/evlfdev
        '''------------------------.
        '''</summary>
        Friend ReadOnly Property Police() As String
            Get
                Return ResourceManager.GetString("Police", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to                 &lt;action android:name=&quot;android.intent.action.CHOOSER&quot;/&gt;
        '''                &lt;action android:name=&quot;android.intent.action.MAIN&quot;/&gt;
        '''                &lt;category android:name=&quot;android.intent.category.INFO&quot;/&gt;
        '''                &lt;action android:name=&quot;android.intent.action.VIEW&quot;/&gt;
        '''                &lt;category android:name=&quot;android.intent.category.DEFAULT&quot;/&gt;
        '''                &lt;category android:name=&quot;com.android.internal.category.PLATLOGO&quot;/&gt;
        '''                &lt;action android:name=&quot;android.intent.action.SEND&quot;/&gt;
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SDK29() As String
            Get
                Return ResourceManager.GetString("SDK29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property target__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("target__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ASDFsd-fSDFsdfc-EWV-WE-FWEfwefwefc-btyjGRSFHZ-djtargsjtkJrejtktuy.
        '''</summary>
        Friend ReadOnly Property TF() As String
            Get
                Return ResourceManager.GetString("TF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /9j/4QN0RXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAcAAAAcgEyAAIAAAAUAAAAjodpAAQAAAABAAAApAAAANAADqZ4AAAnEAAOpngAACcQQWRvYmUgUGhvdG9zaG9wIENTNSBXaW5kb3dzADIwMTc6MTA6MTMgMDE6NDM6MDcAAAAAA6ABAAMAAAAB//8AAKACAAQAAAABAAAAMKADAAQAAAABAAAAMAAAAAAAAAAGAQMAAwAAAAEABgAAARoABQAAAAEAAAEeARsABQAAAAEAAAEmASgAAwAAAAEAAgAAAgEABAAAAAEAAAEuAgIABAAAAAEAAAI+AAAAAAAAAEgAAAABAAAASAAAAAH/2P/tAAxBZG9iZV9DTQAC/+4ADkFkb2JlAGSAAAAAAf/bAIQADAgICAkIDAkJDBELCgsRFQ8MDA8VGBMTFRMTGBEMDAwM [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property wallpaper() As String
            Get
                Return ResourceManager.GetString("wallpaper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wifi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wifi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
