'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7771:7772")>  _
        Public Property ports() As String
            Get
                Return CType(Me("ports"),String)
            End Get
            Set
                Me("ports") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Normal")>  _
        Public Property performance() As String
            Get
                Return CType(Me("performance"),String)
            End Get
            Set
                Me("performance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UTF8")>  _
        Public Property encoding8() As String
            Get
                Return CType(Me("encoding8"),String)
            End Get
            Set
                Me("encoding8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property show_alert() As String
            Get
                Return CType(Me("show_alert"),String)
            End Get
            Set
                Me("show_alert") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Right")>  _
        Public Property location() As String
            Get
                Return CType(Me("location"),String)
            End Get
            Set
                Me("location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Just tell me")>  _
        Public Property disconnected() As String
            Get
                Return CType(Me("disconnected"),String)
            End Get
            Set
                Me("disconnected") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("No")>  _
        Public Property Auto_focus() As String
            Get
                Return CType(Me("Auto_focus"),String)
            End Get
            Set
                Me("Auto_focus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Normal")>  _
        Public Property Effects_CAM() As String
            Get
                Return CType(Me("Effects_CAM"),String)
            End Get
            Set
                Me("Effects_CAM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Streets")>  _
        Public Property Style_Maps() As String
            Get
                Return CType(Me("Style_Maps"),String)
            End Get
            Set
                Me("Style_Maps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property Saving_data() As String
            Get
                Return CType(Me("Saving_data"),String)
            End Get
            Set
                Me("Saving_data") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Auto")>  _
        Public Property CAMQuality() As String
            Get
                Return CType(Me("CAMQuality"),String)
            End Get
            Set
                Me("CAMQuality") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Hacked")>  _
        Public Property build_text_name_victim() As String
            Get
                Return CType(Me("build_text_name_victim"),String)
            End Get
            Set
                Me("build_text_name_victim") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CypherRat")>  _
        Public Property build_text_name_patch() As String
            Get
                Return CType(Me("build_text_name_patch"),String)
            End Get
            Set
                Me("build_text_name_patch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0.0.0")>  _
        Public Property build_text_version() As String
            Get
                Return CType(Me("build_text_version"),String)
            End Get
            Set
                Me("build_text_version") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property build_text_sleep() As Integer
            Get
                Return CType(Me("build_text_sleep"),Integer)
            End Get
            Set
                Me("build_text_sleep") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7771")>  _
        Public Property build_text_port() As Integer
            Get
                Return CType(Me("build_text_port"),Integer)
            End Get
            Set
                Me("build_text_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property build_Checked_hide() As Boolean
            Get
                Return CType(Me("build_Checked_hide"),Boolean)
            End Get
            Set
                Me("build_Checked_hide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property build_Checked_icon() As Boolean
            Get
                Return CType(Me("build_Checked_icon"),Boolean)
            End Get
            Set
                Me("build_Checked_icon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property build_Checked_doze() As Boolean
            Get
                Return CType(Me("build_Checked_doze"),Boolean)
            End Get
            Set
                Me("build_Checked_doze") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("null")>  _
        Public Property build_path_icon() As String
            Get
                Return CType(Me("build_path_icon"),String)
            End Get
            Set
                Me("build_path_icon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("null")>  _
        Public Property build_DGV_list() As String
            Get
                Return CType(Me("build_DGV_list"),String)
            End Get
            Set
                Me("build_DGV_list") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("95, 95, 250")>  _
        Public Property DefaultColorForeground() As Global.System.Drawing.Color
            Get
                Return CType(Me("DefaultColorForeground"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DefaultColorForeground") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50, 50, 50")>  _
        Public Property DefaultColorBackground() As Global.System.Drawing.Color
            Get
                Return CType(Me("DefaultColorBackground"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DefaultColorBackground") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property FontSize() As Integer
            Get
                Return CType(Me("FontSize"),Integer)
            End Get
            Set
                Me("FontSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Regular")>  _
        Public Property FontStyle() As String
            Get
                Return CType(Me("FontStyle"),String)
            End Get
            Set
                Me("FontStyle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00110000")>  _
        Public Property EncryptionKey() As String
            Get
                Return CType(Me("EncryptionKey"),String)
            End Get
            Set
                Me("EncryptionKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property DefaultColor_NewColorFiles() As Global.System.Drawing.Color
            Get
                Return CType(Me("DefaultColor_NewColorFiles"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DefaultColor_NewColorFiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Blue")>  _
        Public Property DefaultColor_ColorTitles() As Global.System.Drawing.Color
            Get
                Return CType(Me("DefaultColor_ColorTitles"),Global.System.Drawing.Color)
            End Get
            Set
                Me("DefaultColor_ColorTitles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("null")>  _
        Public Property BIND_Path() As String
            Get
                Return CType(Me("BIND_Path"),String)
            End Get
            Set
                Me("BIND_Path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("null")>  _
        Public Property BIND_EX() As String
            Get
                Return CType(Me("BIND_EX"),String)
            End Get
            Set
                Me("BIND_EX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("null")>  _
        Public Property intent() As String
            Get
                Return CType(Me("intent"),String)
            End Get
            Set
                Me("intent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NOTI_SOUND() As Boolean
            Get
                Return CType(Me("NOTI_SOUND"),Boolean)
            End Get
            Set
                Me("NOTI_SOUND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property Flags_Visible() As String
            Get
                Return CType(Me("Flags_Visible"),String)
            End Get
            Set
                Me("Flags_Visible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("32px")>  _
        Public Property Flags_Size() As String
            Get
                Return CType(Me("Flags_Size"),String)
            End Get
            Set
                Me("Flags_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property Round() As String
            Get
                Return CType(Me("Round"),String)
            End Get
            Set
                Me("Round") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property SStatus_Visible() As String
            Get
                Return CType(Me("SStatus_Visible"),String)
            End Get
            Set
                Me("SStatus_Visible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0123456789")>  _
        Public Property _Columns() As String
            Get
                Return CType(Me("_Columns"),String)
            End Get
            Set
                Me("_Columns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Small")>  _
        Public Property FM_IC_Size() As String
            Get
                Return CType(Me("FM_IC_Size"),String)
            End Get
            Set
                Me("FM_IC_Size") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property Removing_Duplicates() As String
            Get
                Return CType(Me("Removing_Duplicates"),String)
            End Get
            Set
                Me("Removing_Duplicates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property _multi_sounds() As String
            Get
                Return CType(Me("_multi_sounds"),String)
            End Get
            Set
                Me("_multi_sounds") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property ImageQualty() As Integer
            Get
                Return CType(Me("ImageQualty"),Integer)
            End Get
            Set
                Me("ImageQualty") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property Cashpic() As String
            Get
                Return CType(Me("Cashpic"),String)
            End Get
            Set
                Me("Cashpic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yes")>  _
        Public Property LOG() As String
            Get
                Return CType(Me("LOG"),String)
            End Get
            Set
                Me("LOG") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PT1BQUFic2RGQURhY0FTQ1ZERVNEVnNkU0RSVlNEVkFFR1NTRkJSRUE=")>  _
        Public Property DKEY() As String
            Get
                Return CType(Me("DKEY"),String)
            End Get
            Set
                Me("DKEY") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AngelAndroid_v2.My.MySettings
            Get
                Return Global.AngelAndroid_v2.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
